<a href="https://colab.research.google.com/github/chandu01432/Upskill/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# create the arrays

a = np.array([1,2,3,4])
a




array([1, 2, 3, 4])

In [ ]:
a = np.array([[1,2,3,4], [44,5,6,7]])
a



array([[ 1,  2,  3,  4],
       [44,  5,  6,  7]])

In [ ]:
o = np.ones((3,4),dtype = int)
o

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
o = np.zeros((3,4),dtype = int)
o

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
o = np.ones((3,4),dtype = int)*3
o

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [ ]:
o = np.full((3,4),3)
o

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [ ]:
# random floating numbers between a range of 10 to 100

r =10+(100-10)*np.random.random((3,3))
r

array([[35.58936308, 54.17296001, 26.86857018],
       [26.50753446, 12.30850229, 39.8984397 ],
       [44.82549203, 15.14412417, 97.63005203]])

In [ ]:
ri = np.random.randint(10,100,(3,3))
ri

array([[78, 60, 13],
       [38, 95, 63],
       [61, 10, 27]])

In [ ]:
# (start,end, steps)

ar = np.arange(0,101,1)
ar

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
# between 10 to 100 i want 10 numbers with 10 starting and ending 100 with equal gaps between each numbers
li = np.linspace(10,100,13)
li

array([ 10. ,  17.5,  25. ,  32.5,  40. ,  47.5,  55. ,  62.5,  70. ,
        77.5,  85. ,  92.5, 100. ])

In [ ]:
# Array inspection

o.shape

(3, 4)

In [ ]:
o.size

12

In [ ]:
o.ndim

2

In [ ]:
o.dtype

dtype('int64')

In [ ]:
o

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [ ]:
# Modifying the shape

In [ ]:
o.shape = (3,4)

In [ ]:
o = o.reshape(12,1)
o

array([[3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3]])

In [ ]:
o

array([[3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3]])

In [ ]:
# Math function

print("Exponents of an array", np.exp(o))
print("Log of an array", np.log(o))
print("Square Root of an array", np.sqrt(o))
print("Mean", np.mean(o))
print("Median", np.median(o))
print("std", np.std(o))
print("Square Power", np.power(o, 2))
print("Sin", np.sin(o))
print("Cos", np.cos(o))

Exponents of an array [[20.08553692]
 [20.08553692]
 [20.08553692]
 [20.08553692]
 [20.08553692]
 [20.08553692]
 [20.08553692]
 [20.08553692]
 [20.08553692]
 [20.08553692]
 [20.08553692]
 [20.08553692]]
Log of an array [[1.09861229]
 [1.09861229]
 [1.09861229]
 [1.09861229]
 [1.09861229]
 [1.09861229]
 [1.09861229]
 [1.09861229]
 [1.09861229]
 [1.09861229]
 [1.09861229]
 [1.09861229]]
Square Root of an array [[1.73205081]
 [1.73205081]
 [1.73205081]
 [1.73205081]
 [1.73205081]
 [1.73205081]
 [1.73205081]
 [1.73205081]
 [1.73205081]
 [1.73205081]
 [1.73205081]
 [1.73205081]]
Mean 3.0
Median 3.0
std 0.0
Square Power [[9]
 [9]
 [9]
 [9]
 [9]
 [9]
 [9]
 [9]
 [9]
 [9]
 [9]
 [9]]
Sin [[0.14112001]
 [0.14112001]
 [0.14112001]
 [0.14112001]
 [0.14112001]
 [0.14112001]
 [0.14112001]
 [0.14112001]
 [0.14112001]
 [0.14112001]
 [0.14112001]
 [0.14112001]]
Cos [[-0.9899925]
 [-0.9899925]
 [-0.9899925]
 [-0.9899925]
 [-0.9899925]
 [-0.9899925]
 [-0.9899925]
 [-0.9899925]
 [-0.9899925]
 [-0.9899925]


In [ ]:
ri = np.random.randint(10,100,(4,4))
ri

array([[90, 87, 77, 74],
       [49, 36, 91, 83],
       [53, 91, 11, 32],
       [45, 18, 39, 79]])

In [ ]:
# indexing and slicing

ri[0][-1]

np.int64(74)

In [ ]:
# [start:stop(excluding):steps]

ri[2::,2::]

array([[11, 32],
       [39, 79]])

In [ ]:
ri[1::2,-1::-2]

array([[83, 36],
       [79, 18]])

In [ ]:
np.sum([[1,2],[5,6]])

np.int64(14)

In [ ]:
a = np.array([[1,2],[5,6]])
b = np.array([[10,20],[50,60]])

In [ ]:
np.add(a,b)

array([[11, 22],
       [55, 66]])

In [ ]:
np.multiply(a,b)

array([[ 10,  40],
       [250, 360]])

In [ ]:
np.divide(a,b)

array([[0.1, 0.1],
       [0.1, 0.1]])

In [ ]:
np.subtract(a,b)

array([[ -9, -18],
       [-45, -54]])

In [ ]:
a = np.array([1,2,3])
b = np.array([10,50,60])
c = np.array([1,2,3])
np.array_equal(a,b)
np.equal(a,c)

array([ True,  True,  True])

In [ ]:
np.hstack((a,b,c))

array([ 1,  2,  3, 10, 50, 60,  1,  2,  3])

In [ ]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [10, 50, 60]])

In [ ]:
# a = np.array([[1,2,3],[10,50,60]])
# c = np.array([1,2,3])

In [ ]:
np.vstack((a,c))

array([[ 1,  2,  3],
       [10, 50, 60],
       [ 1,  2,  3]])

In [ ]:
np.column_stack((a,b,c))

array([[ 1, 10,  1],
       [ 2, 50,  2],
       [ 3, 60,  3]])