<a href="https://colab.research.google.com/github/chandu01432/Upskill/blob/main/numpy%20handson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# create  two numpy  array with data types integer , float
# [1,2,3,4,5,6]
# print the array
# know the data type of the numpy array

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,6], dtype="int")

In [ ]:
print(a)

[1 2 3 4 5 6]


In [ ]:
print(a.dtype)

int64


In [ ]:
a = np.array([1,2,3,4,5,6], dtype="float")

In [ ]:
print(a)

[1. 2. 3. 4. 5. 6.]


In [ ]:
print(a.dtype)

float64


In [ ]:
# create numpy arrays having dimensions zero, one , two , three respectively.
# print the shape and dimensions of those arrays

In [ ]:
# zero dimensional array
zero_d = np.array(56)

In [ ]:
print(zero_d)

56


In [ ]:
print(zero_d.ndim)

0


In [ ]:
print(zero_d.shape)

()


In [ ]:
# 1-D array
one_d = np.array([1,2,3,4])

In [ ]:
print(one_d)

[1 2 3 4]


In [ ]:
print(one_d.ndim)

1


In [ ]:
print(one_d.shape)

(4,)


In [ ]:
# 2-D array
two_d = np.array([[1,2,3,4,10], [5,6,7,8,50]])

In [ ]:
print(two_d)

[[ 1  2  3  4 10]
 [ 5  6  7  8 50]]


In [ ]:
print(two_d.ndim)

2


In [ ]:
print(two_d.shape)

(2, 5)


In [ ]:
# practise for 3-D also

In [ ]:
# create 2*2 , 3*3 , 4*4, 4*6 indentity matrix using numpy


In [ ]:
two_ide = np.identity(2, dtype = "int")

In [ ]:
print(two_ide)

[[1 0]
 [0 1]]


In [ ]:
three_ide = np.identity(3, dtype = "int")

In [ ]:
print(three_ide)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
four_ide = np.identity(4, dtype = "int")

In [ ]:
print(four_ide)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
x = np.eye(4,6)

In [ ]:
print(x)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


In [ ]:
# Create an array with shape 2,5 and all the elements should be zero
a = np.zeros((2,5), dtype = "int")


In [ ]:
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
# create a numpy array  with shape 3*5 and all the elements should be 55

In [ ]:
x = np.full((3,5), 55)  # 1st method
print(x)

[[55 55 55 55 55]
 [55 55 55 55 55]
 [55 55 55 55 55]]


In [ ]:
x1 = np.ones((3,5), dtype = "int") * 55  # 2nd method
print(x1)

[[55 55 55 55 55]
 [55 55 55 55 55]
 [55 55 55 55 55]]


In [ ]:
# create a numpy array with random integers in the range from 0 to 100
# the sample size(number of elements) should be 25
# after this  , give me all the unique elements in the array

In [ ]:
#np.random.seed(0)  # fix the values
arr = np.random.randint(0,100,size = 25)
print(arr)

[49 69 41 35 64 95 69 94  0 50 36 34 48 93  3 98 42 77 21 73  0 10 43 58
 23]


In [ ]:
arr_uni = np.unique(arr)
print(arr_uni)

[ 2 13 16 24 27 28 30 32 34 35 36 44 52 53 55 57 75 76 82 83 93]


In [ ]:
print(arr_uni.shape)

(21,)


In [ ]:
# dice = [1,2,3,4,5,6]
# everytime i run the code , i want a random value from the dice

In [ ]:
import random
dice=[1,2,3,4,5,6]
roll=random.choice(dice)
print(roll)

1


In [ ]:
# create a numpy array with shape 2*3 with random integers in range 0 to 100
# reshape the array with the shape 3*2 and print the updated  shape of the array

In [ ]:
array1=np.random.randint(0,100,size=(2,3))
print(array1)


[[36 10 86]
 [43 11  2]]


In [ ]:
array2 = array1.reshape(3,2)
print(array2)

[[36 10]
 [86 43]
 [11  2]]


In [ ]:
# create a 5*5 matrix , fill it with random integers in the range 0,100
# replace all values greater than 50 with 290 , print the modified array
# ex - 62 - 290

In [ ]:
arr = np.random.randint(0,101,size= (5,5))
arr


array([[ 66,  52,  67,  61,  14],
       [ 96,   4,  67,  11,  86],
       [ 77,  75,  56,  16,  24],
       [ 29,  21,  25,  80,  60],
       [ 61,  83,  33,  32, 100]])

In [ ]:
arr[arr > 50] = 290
arr

array([[290, 290, 290, 290,  14],
       [290,   4, 290,  11, 290],
       [290, 290, 290,  16,  24],
       [ 29,  21,  25, 290, 290],
       [290, 290,  33,  32, 290]])

In [ ]:
# create a numpy array of numbers from 1-20, use the arange fn
# do something to extract only even numbers

In [ ]:
a=np.arange(1,21)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
even_num=a[a%2==0]
even_num

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
# arr = [10,20,30,40,50]
# insert 100 between every two elements - HW

In [ ]:
# stack - joining mulitple arrays along a new axis

In [ ]:
a = np.array([10,20,30])
b = np.array([40,50,60])

result = np.stack((a,b)) # axis = 0
print(result)

[[10 20 30]
 [40 50 60]]


In [ ]:
result = np.stack((a,b), axis = 1)
print(result)

[[10 40]
 [20 50]
 [30 60]]


In [ ]:
# hstack ,vstack


In [ ]:
a = np.array([10,20,30])
b = np.array([40,50,60])

In [ ]:
result = np.hstack((a,b)) # hstack axis joined along - 1
print(result)

[10 20 30 40 50 60]


In [ ]:
result = np.vstack((a,b))  # vstack axis joined along - 0
print(result)

[[10 20 30]
 [40 50 60]]


In [ ]:
# create a random numpy array  , range - 0,100 , sample size - 50
# print the first 10 elements
# print the last 10 elements using positive indexing
# print the last 10 elements using negative indexing
# print the elements from index 10 to 20
# print the element at index 25
# print the entire array using negative indexing


In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(0,100,size = 50)
print(arr)

[65 67 10  8 62  2 66 48 37 86 34 41 90 82 89 16  9 93 98 52 19 18 34  4
 55 73 91 70 84 56 72 54 57 75 65 80 36 73 99  0 82 81 84 13 23 26  2 52
 14 23]


In [ ]:
arr[0:10]  # start index : stop index : step- size

array([65, 67, 10,  8, 62,  2, 66, 48, 37, 86])

In [ ]:
arr[40:50]

array([82, 81, 84, 13, 23, 26,  2, 52, 14, 23])

In [ ]:
arr[-10:]

array([82, 81, 84, 13, 23, 26,  2, 52, 14, 23])

In [ ]:
arr[25]

np.int64(73)

In [ ]:
arr[-50:]

array([65, 67, 10,  8, 62,  2, 66, 48, 37, 86, 34, 41, 90, 82, 89, 16,  9,
       93, 98, 52, 19, 18, 34,  4, 55, 73, 91, 70, 84, 56, 72, 54, 57, 75,
       65, 80, 36, 73, 99,  0, 82, 81, 84, 13, 23, 26,  2, 52, 14, 23])

In [ ]:
arr[::-1]

array([23, 14, 52,  2, 26, 23, 13, 84, 81, 82,  0, 99, 73, 36, 80, 65, 75,
       57, 54, 72, 56, 84, 70, 91, 73, 55,  4, 34, 18, 19, 52, 98, 93,  9,
       16, 89, 82, 90, 41, 34, 86, 37, 48, 66,  2, 62,  8, 10, 67, 65])